const INSTITUTION_ICON_URLS: Record<string, string> = {
  // 은행
  'shinhan-bank': new URL('../../../icons/bank/icn-bank-shinhan.svg', import.meta.url).href,
  'kb-bank': new URL('../../../icons/bank/icn-bank-kb.svg', import.meta.url).href,
  'woori-bank': new URL('../../../icons/bank/icn-bank-woori.svg', import.meta.url).href,
  'hana-bank': new URL('../../../icons/bank/icn-bank-hana.svg', import.meta.url).href,
  'nh-bank': new URL('../../../icons/bank/icn-bank-nh.svg', import.meta.url).href,
  'kakao-bank': new URL('../../../icons/bank/icn-bank-kakao.svg', import.meta.url).href,
  'toss-bank': new URL('../../../icons/bank/icn-bank-toss.svg', import.meta.url).href,
  'kbank-bank': new URL('../../../icons/bank/icn-bank-kbank.svg', import.meta.url).href,
  'ibk-bank': new URL('../../../icons/bank/icn-bank-ibk.svg', import.meta.url).href,
  'dgb-bank': new URL('../../../icons/bank/icn-bank-dgb.svg', import.meta.url).href,
  'bnk-busan-bank': new URL('../../../icons/bank/icn-bank-bnk.svg', import.meta.url).href,
  'bnk-gyeongnam-bank': new URL('../../../icons/bank/icn-bank-bnk.svg', import.meta.url).href,
  'kwangju-bank': new URL('../../../icons/bank/icn-bank-kwangju.svg', import.meta.url).href,
  'jeju-bank': new URL('../../../icons/bank/icn-bank-jeju.svg', import.meta.url).href,
  'kdb-bank': new URL('../../../icons/bank/icn-bank-kdb.svg', import.meta.url).href,
  'sc-bank': new URL('../../../icons/bank/icn-bank-sc.svg', import.meta.url).href,
  'citi-bank': new URL('../../../icons/bank/icn-bank-citi.svg', import.meta.url).href,
  'mg-bank': new URL('../../../icons/bank/icn-bank-mg.svg', import.meta.url).href,
  'cu-bank': new URL('../../../icons/bank/icn-bank-cu.svg', import.meta.url).href,
  'suhyup-bank': new URL('../../../icons/bank/icn-bank-suhyup.svg', import.meta.url).href,
  'postoffice-bank': new URL('../../../icons/bank/icn-bank-postoffice.svg', import.meta.url).href,
  'sb-bank': new URL('../../../icons/bank/icn-bank-sb.svg', import.meta.url).href,
  'junbuk-bank': new URL('../../../icons/bank/icn-bank-junbuk.svg', import.meta.url).href,
  'sbi-bank': new URL('../../../icons/bank/icn-bank-sbi.svg', import.meta.url).href,
  'deutsche-bank': new URL('../../../icons/bank/icn-bank-deutsche.svg', import.meta.url).href,
  'boa-bank': new URL('../../../icons/bank/icn-bank-boa.svg', import.meta.url).href,
  'hsbc-bank': new URL('../../../icons/bank/icn-bank-hsbc.svg', import.meta.url).href,
  'bankofchina-bank': new URL('../../../icons/bank/icn-bank-bankofchina.svg', import.meta.url).href,
  'jpmorgan-bank': new URL('../../../icons/bank/icn-bank-jpmorgan.svg', import.meta.url).href,
  'nfcf-bank': new URL('../../../icons/bank/icn-bank-nfcf.svg', import.meta.url).href,
  'chinaconstruction-bank': new URL('../../../icons/bank/icn-bank-chinaconstruction.svg', import.meta.url).href,
  'bnp-bank': new URL('../../../icons/bank/icn-bank-bnp.svg', import.meta.url).href,

  // 증권
  'koreainvestment-sec': new URL(
    '../../../icons/Stock/icn-securities-koreainvestment.svg',
    import.meta.url,
  ).href,
  'miraeasset-sec': new URL('../../../icons/Stock/icn-securities-miraeasset.svg', import.meta.url).href,
  'samsung-sec': new URL('../../../icons/Stock/icn-securities-samsung.svg', import.meta.url).href,
  'kb-sec': new URL('../../../icons/Stock/icn-securities-kb.svg', import.meta.url).href,
  'nhqv-sec': new URL('../../../icons/Stock/icn-securities-nhqv.svg', import.meta.url).href,
  'daishin-sec': new URL('../../../icons/Stock/icn-securities-daishin.svg', import.meta.url).href,
  'meritz-sec': new URL('../../../icons/Stock/icn-securities-meritz.svg', import.meta.url).href,
  'sk-sec': new URL('../../../icons/Stock/icn-securities-sk.svg', import.meta.url).href,
  'kium-sec': new URL('../../../icons/Stock/icn-securities-kium.svg', import.meta.url).href,
  'shinyoung-sec': new URL('../../../icons/Stock/icn-securities-shinyoung.svg', import.meta.url).href,
  'eugene-sec': new URL('../../../icons/Stock/icn-securities-eugene.svg', import.meta.url).href,
  'hanhwa-sec': new URL('../../../icons/Stock/icn-securities-hanhwa.svg', import.meta.url).href,
  'ls-sec': new URL('../../../icons/Stock/icn-securities-ls.svg', import.meta.url).href,
  'db-sec': new URL('../../../icons/Stock/icn-securities-db.svg', import.meta.url).href,
  'shinhan-sec': new URL('../../../icons/Stock/icn-securities-shinhan.svg', import.meta.url).href,
  'hana-sec': new URL('../../../icons/Stock/icn-securities-hana.svg', import.meta.url).href,
  'toss-sec': new URL('../../../icons/Stock/icn-securities-toss.svg', import.meta.url).href,
  'woori-sec': new URL('../../../icons/Stock/icn-securities-woori.svg', import.meta.url).href,
  'hyundai-sec': new URL('../../../icons/Stock/icn-securities-hyundai.svg', import.meta.url).href,
  'yuanta-sec': new URL('../../../icons/Stock/icn-securities-yuanta.svg', import.meta.url).href,
  'kyobo-sec': new URL('../../../icons/Stock/icn-securities-kyobo.svg', import.meta.url).href,
  'bnk-sec': new URL('../../../icons/Stock/icn-securities-bnk.svg', import.meta.url).href,
  'ibk-sec': new URL('../../../icons/Stock/icn-securities-ibk.svg', import.meta.url).href,
  'kakaopay-sec': new URL('../../../icons/Stock/icn-securities-kakaopay.svg', import.meta.url).href,
  'daol-sec': new URL('../../../icons/Stock/icn-securities-daol.svg', import.meta.url).href,
  'bookook-sec': new URL('../../../icons/Stock/icn-securities-bookook.svg', import.meta.url).href,
  'sangsangin-sec': new URL('../../../icons/Stock/icn-securities-sangsangin.svg', import.meta.url).href,
  'hanyang-sec': new URL('../../../icons/Stock/icn-securities-hanyang.svg', import.meta.url).href,
  'dgb-sec': new URL('../../../icons/Stock/icn-securities-dgb.svg', import.meta.url).href,
  'namuh-sec': new URL('../../../icons/Stock/icn-securities-namuh.svg', import.meta.url).href,
  'cape-sec': new URL('../../../icons/Stock/icn-securities-cape.svg', import.meta.url).href,
  'fosskorea-sec': new URL('../../../icons/Stock/icn-securities-fosskorea.svg', import.meta.url).href,

  // 보험 (손해)
  'samsung-fire': new URL('../../../icons/insurance/icn-insurance-samsung-fire.svg', import.meta.url).href,
  'db-fire': new URL('../../../icons/insurance/icn-insurance-db-fire.svg', import.meta.url).href,
  'hanhwa-fire': new URL('../../../icons/insurance/icn-insurance-hanhwa-fire.svg', import.meta.url).href,
  'meritz-fire': new URL('../../../icons/insurance/icn-insurance-meritz-fire.svg', import.meta.url).href,
  'kb-fire': new URL('../../../icons/insurance/icn-insurance-kb-fire.svg', import.meta.url).href,
  'hyundai-fire': new URL('../../../icons/insurance/icn-insurance-hyundai-fire.svg', import.meta.url).href,
  'lotte-fire': new URL('../../../icons/insurance/icn-insurance-lotte-fire.svg', import.meta.url).href,
  'nh-fire': new URL('../../../icons/insurance/icn-insurance-nh-fire.svg', import.meta.url).href,
  'heungkuk-fire': new URL('../../../icons/insurance/icn-insurance-heungkuk-fire.svg', import.meta.url).href,
  'axa-fire': new URL('../../../icons/insurance/icn-insurance-axa-fire.svg', import.meta.url).href,
  'ace-american-fire': new URL('../../../icons/insurance/icn-insurance-ace-american-fire.svg', import.meta.url).href,

  // 보험 (생명)
  'kyobo-life': new URL('../../../icons/insurance/icn-insurance-kyobo-life.svg', import.meta.url).href,
  'samsung-life': new URL('../../../icons/insurance/icn-insurance-samsung-life.svg', import.meta.url).href,
  'shinhan-life': new URL('../../../icons/insurance/icn-insurance-shinhan-life.svg', import.meta.url).href,
  'hanhwa-life': new URL('../../../icons/insurance/icn-insurance-hanhwa-life.svg', import.meta.url).href,
  'kb-life': new URL('../../../icons/insurance/icn-insurance-kb-life.svg', import.meta.url).href,
  'nh-life': new URL('../../../icons/insurance/icn-insurance-nh-life.svg', import.meta.url).href,
  'db-life': new URL('../../../icons/insurance/icn-insurance-db-life.svg', import.meta.url).href,
  'hyundai-life': new URL('../../../icons/insurance/icn-insurance-hyundai-life.svg', import.meta.url).href,
  'heungkuk-life': new URL('../../../icons/insurance/icn-insurance-heungkuk-life.svg', import.meta.url).href,
  'miraeasset-life': new URL('../../../icons/insurance/icn-insurance-miraeasset-life.svg', import.meta.url).href,
  'prudential-life': new URL('../../../icons/insurance/icn-insurance-prudential-life.svg', import.meta.url).href,
  'aia-life': new URL('../../../icons/insurance/icn-insurance-aia-life.svg', import.meta.url).href,
  'lina-life': new URL('../../../icons/insurance/icn-insurance-lina-life.svg', import.meta.url).href,
  'dongyang-life': new URL('../../../icons/insurance/icn-insurance-dongyang-life.svg', import.meta.url).href,
  'abl-life': new URL('../../../icons/insurance/icn-insurance-abl-life.svg', import.meta.url).href,
  'chubb-life': new URL('../../../icons/insurance/icn-insurance-chubb-life.svg', import.meta.url).href,
  'orange-life': new URL('../../../icons/insurance/icn-insurance-orange-life.svg', import.meta.url).href,
  'kyobo-lifeplanet-life': new URL(
    '../../../icons/insurance/icn-insurance-kyobo-lifeplanet-life.svg',
    import.meta.url,
  ).href,
  'kdb-life': new URL('../../../icons/insurance/icn-insurance-kdb-life.svg', import.meta.url).href,
  'dgb-life': new URL('../../../icons/insurance/icn-insurance-dgb-life.svg', import.meta.url).href,
  'ibk-pension': new URL('../../../icons/insurance/icn-insurance-ibk-pension.svg', import.meta.url).href,
}

export function getInstitutionIconUrl(iconKey: string): string | undefined {
  return INSTITUTION_ICON_URLS[iconKey]
}
